version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      slidev:
        patterns:
          - '@slidev/*'
      eslint:
        patterns:
          - 'eslint*'
          - 'typescript-eslint'
      prettier:
        patterns:
          - 'prettier*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
